### ISSUE TITLE
Error in Hawkeye using simple_plants demo

### ISSUE THREAD

**Issue by jhill1** [willpearse/phyloGenerator2#13]
Edited simple plants demo to use hawkeye (bottom line change in important):

```
jhill1@rheic ~/work/software/phyloGenerator2 $ diff demo/simple_plants_he/params.yml demo/simple_plants/params.yml 
16c16
< species: /home/jhill1/work/software/phyloGenerator2/demo/simple_plants_he/leipzig.txt
---
> species: /home/will/Code/phyloGenerator2/demo/simple_plants/species.txt
19c19
< working_dir: /home/jhill1/work/software/phyloGenerator2/demo/simple_plants_he
---
> working_dir: /home/will/test
21c21
< email: jon.hill@york.ac.uk
---
> email: your@email.here
32c32
<     ref_file: /home/jhill1/work/software/phyloGenerator2/demo/simple_plants_he/rbcL_reference.fasta
---
>     ref_file: /home/will/Code/phyloGenerator2/demo/simple_plants/rbcL_reference.fasta
40c40
<     ref_file: /home/jhill1/work/software/phyloGenerator2/demo/simple_plants_he/matK_reference.fasta
---
>     ref_file: /home/will/Code/phyloGenerator2/demo/simple_plants/matK_reference.fasta
60c60
< hawkeye: true
---
> #hawkeye: true
```

Gives following error:

```
jhill1@rheic ~/work/software/phyloGenerator2 $ ruby pG_2.rb demo/simple_plants_he/params.yml 
phyloGenerator 2.0-2 DOI: 10.1111/2041-210X.12055
Please *use with caution*; first version!
Will Pearse - will.pearse@gmail.com
 - Setup complete...
 - - rbcL: 143/182 sequences found
 - - matK: 106/182 sequences found
 - Download complete...
/home/jhill1/work/software/phyloGenerator2/lib/Hawkeye.rb:40:in `check': undefined local variable or method `verbose' for #<Hawkeye:0x00000002d18b50> (NameError)
	from /home/jhill1/work/software/phyloGenerator2/lib/Cap.rb:48:in `block (2 levels) in check'
```

**Comment by willpearse** [comment]
Can't say I'm fast, but it's fixed. Thanks Jon!!!
